# Generated by Django 3.2 on 2021-04-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.TextField()),
                ('kodematakuliah', models.TextField()),
                ('jenistugas', models.TextField()),
                ('topiktugas', models.TextField()),
            ],
        ),
    ]
