# Generated by Django 3.2 on 2021-04-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_alter_task_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
